### PR TITLE
Mayhem Integration

### PR DESCRIPTION
**Pull request by code-terror**
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Summary about this PR

## Changelog

- New Feature
- Bug Fix
- Improvement
- Performance Improvement
- Build/Testing/CI
- Documentation
- Not for changelog (changelog entry is not required)

## Related Issues

Fixes #issue

### CODE REVIEW

**Comment by code-terror** [comment]
> hey @code-terror could you make a whitespace change and push--trying to determine why the action is failing, but it's been a while since your last push and I want to see if it'll work now

I have ran the action again..It works..It failed before due to rate limiting.. and the naming convention of the target..It works now

**Comment by code-terror** [comment]
@noahShinabarger

**Review by xansec — APPROVED** [review]
According to the last run on @code-terror's branch, this seems to be passing now. Accepting. LGTM!

**Comment by xansec** [comment]
@code-terror The action that just ran seems to be failing:
https://github.com/mayhemheroes/risingwave/runs/7532414112?check_suite_focus=true

Could you please make sure to install openssl and pkg-config in the (package) Docker image and rerun? If it works on your branch, you can submit another PR to this repo resolving the error.

**Comment by code-terror** [comment]
When i am trying to create a pull request, the fork from mayhemheros is not showing up on the list..any idea what is causing this error? refer to screenshot.
image

**Comment by code-terror** [comment]
@xansec

**Comment by xansec** [comment]
Not sure why it's not showing up, but you can construct the URL manually. Try this:
https://github.com/mayhemheroes/databend/compare/main...code-terror:databend:main

Make sure you sync from upstream first to avoid merge conflicts.

**Pull request merged**
